# 基本配置
title: Pizicai's Tech Blog
description: 技术探索与实践 | DevOps | LLM | Web3 | Physics
author: Pizicai
url: "https://pizicaiman.github.io"
baseurl: ""
language: zh-CN

# 主题设置
theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge

# 文章路径配置
collections:
  docs:
    output: true
    permalink: /:path/

# 默认布局设置
defaults:
  - scope:
      path: "docs/cloudnative"
      type: "pages"
    values:
      layout: "doc"
      category: "cloudnative"
  - scope:
      path: "docs/llm"
      type: "pages"
    values:
      layout: "doc"
      category: "llm"
  - scope:
      path: "docs/maths"
      type: "pages"
    values:
      layout: "doc"
      category: "maths"
  - scope:
      path: "docs/web3"
      type: "pages"
    values:
      layout: "doc"
      category: "web3"
  - scope:
      path: "docs/physics"
      type: "pages"
    values:
      layout: "doc"
      category: "physics"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# 导航菜单
navigation:
  - title: 首页
    url: /
  - title: 文档
    url: /docs/
  - title: DevOps
    url: /docs/cloudnative/
    category: cloudnative
  - title: LLM
    url: /docs/llm/
    category: llm
  - title: Maths
    url: /docs/maths/
    category: maths
  - title: Physics
    url: /docs/physics/
    category: physics
  - title: Web3
    url: /docs/web3/
    category: web3
  - title: 关于
    url: /about/

# 分类设置
categories: 
  - cloudnative
  - llm
  - maths
  - physics
  - web3

# 插件配置
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# 分页设置
paginate: 10
paginate_path: "/blog/page:num/"

# 时区和日期格式
timezone: Asia/Shanghai
date_format: "%Y-%m-%d"

# 排除文件
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github

# 社交链接
social:
  github: pizicaiman
  
# SEO 优化
twitter:
  username: pizicaiman